name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: make toolchain
      run:  zsh build_toolchain.sh

    - name: build 
      run: make clean;make

  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: install zsh
      run: sudo apt-get -y install zsh

    - name: install xzutils
      run: sudo apt-get -y install xz-utils

    - name: make toolchain
      run:  zsh build_toolchain.sh

    - name: build 
      run: make clean;make
