name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: make toolchain
      run:  bash -e build_toolchain.sh arm-none-eabi

    - name: build 
      run: make clean;make

  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: make toolchain
      run:  bash3 -e build_toolchain.sh arm-none-eabi

    - name: build 
      run: make clean;make
